### ISSUE TITLE
Should famous-views stay?

### ISSUE THREAD

**Issue by timfam** [SpaceJs/enterprise#1]
I spoke to @gadicc and he said probably too early to add FV still quite buggy. Should we deal with the bugs as we go along or wait?

**Comment by DominikGuzei** [comment]
Hey there,
I have no experience with famous views yet, so i would be reluctant to use them in the example (if none of us knows the potential pitfalls)

There are three options that i already know / would like to use:
* Blaze (with space-ui mediators)
* Blaze Components (with space-ui blaze-components)
* React (need to be implemented, hopefully not hard todo)

**Comment by timfam** [comment]
Famous-views has been dropped
